services:
  app:
    container_name: batikkin-app
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env.prod
    environment:
      - APP_ENV=production
    depends_on:
      - db
    networks:
      - network
  db:
    container_name: batikkin-db
    image: postgres:16.1-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres:
    driver: local
